import { MigrationInterface, QueryRunner } from "typeorm";

export class  $npmConfigName1732619474386 implements MigrationInterface {
    name = ' $npmConfigName1732619474386'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`card_members\` DROP FOREIGN KEY \`FK_e635eb7677b92b43c746afb0c33\``);
        await queryRunner.query(`ALTER TABLE \`card_members\` DROP FOREIGN KEY \`FK_060d5839fbc02bdca25f57a2206\``);
        await queryRunner.query(`ALTER TABLE \`card_members\` CHANGE \`cardIDId\` \`cardIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`card_members\` CHANGE \`userIDId\` \`userIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_5fd7e1818269b78c2740fc27771\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_b202e040bcab8687fa432628fba\``);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`userIDId\` \`userIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`cardIDId\` \`cardIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`cards\` DROP FOREIGN KEY \`FK_2cc808bbdb6f4e1169a8916d0a6\``);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`coverUrl\` \`coverUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`priority\` \`priority\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`startDate\` \`startDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`dueDate\` \`dueDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`listIDId\` \`listIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`lists\` DROP FOREIGN KEY \`FK_35ce69b6248c3fdac997094de16\``);
        await queryRunner.query(`ALTER TABLE \`lists\` CHANGE \`boardIDId\` \`boardIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`board_members\` DROP FOREIGN KEY \`FK_1c326eec837722d2e0879a348cc\``);
        await queryRunner.query(`ALTER TABLE \`board_members\` DROP FOREIGN KEY \`FK_cac1b90399803e9ec4a5e6e52a1\``);
        await queryRunner.query(`ALTER TABLE \`board_members\` CHANGE \`userIDId\` \`userIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`board_members\` CHANGE \`boardIDId\` \`boardIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`boards\` DROP FOREIGN KEY \`FK_1ce74d5411749b559748b9f3276\``);
        await queryRunner.query(`ALTER TABLE \`boards\` DROP FOREIGN KEY \`FK_074efe1a079786d8c076bf00fff\``);
        await queryRunner.query(`ALTER TABLE \`boards\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`boards\` CHANGE \`coverUrl\` \`coverUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`boards\` CHANGE \`visibility\` \`visibility\` enum ('workspace', 'private') NOT NULL DEFAULT 'workspace'`);
        await queryRunner.query(`ALTER TABLE \`boards\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`boards\` CHANGE \`projectId\` \`projectId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP FOREIGN KEY \`FK_361a53ae58ef7034adc3c06f09f\``);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`project_members\` DROP FOREIGN KEY \`FK_24cae15cf042f411ce2ccae3c1f\``);
        await queryRunner.query(`ALTER TABLE \`project_members\` DROP FOREIGN KEY \`FK_d8433ad1d7964e95ddad79d2cfe\``);
        await queryRunner.query(`ALTER TABLE \`project_members\` CHANGE \`userIDId\` \`userIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`project_members\` CHANGE \`projectIDId\` \`projectIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_554429ae7394b1fd4f26f45a623\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`data\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`data\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`userIDId\` \`userIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_ae2afa612c84f4eb307d6c652be\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`avatarUrl\` \`avatarUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`accessToken\` \`accessToken\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`accessTokenExpiresAt\` \`accessTokenExpiresAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`refreshToken\` \`refreshToken\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`refreshTokenExpiresAt\` \`refreshTokenExpiresAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`cardMembersId\` \`cardMembersId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`card_members\` ADD CONSTRAINT \`FK_e635eb7677b92b43c746afb0c33\` FOREIGN KEY (\`cardIDId\`) REFERENCES \`cards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`card_members\` ADD CONSTRAINT \`FK_060d5839fbc02bdca25f57a2206\` FOREIGN KEY (\`userIDId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_5fd7e1818269b78c2740fc27771\` FOREIGN KEY (\`userIDId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_b202e040bcab8687fa432628fba\` FOREIGN KEY (\`cardIDId\`) REFERENCES \`cards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cards\` ADD CONSTRAINT \`FK_2cc808bbdb6f4e1169a8916d0a6\` FOREIGN KEY (\`listIDId\`) REFERENCES \`lists\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`lists\` ADD CONSTRAINT \`FK_35ce69b6248c3fdac997094de16\` FOREIGN KEY (\`boardIDId\`) REFERENCES \`boards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`board_members\` ADD CONSTRAINT \`FK_1c326eec837722d2e0879a348cc\` FOREIGN KEY (\`userIDId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`board_members\` ADD CONSTRAINT \`FK_cac1b90399803e9ec4a5e6e52a1\` FOREIGN KEY (\`boardIDId\`) REFERENCES \`boards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`boards\` ADD CONSTRAINT \`FK_1ce74d5411749b559748b9f3276\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`boards\` ADD CONSTRAINT \`FK_074efe1a079786d8c076bf00fff\` FOREIGN KEY (\`projectId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD CONSTRAINT \`FK_361a53ae58ef7034adc3c06f09f\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_members\` ADD CONSTRAINT \`FK_24cae15cf042f411ce2ccae3c1f\` FOREIGN KEY (\`userIDId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_members\` ADD CONSTRAINT \`FK_d8433ad1d7964e95ddad79d2cfe\` FOREIGN KEY (\`projectIDId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_554429ae7394b1fd4f26f45a623\` FOREIGN KEY (\`userIDId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_ae2afa612c84f4eb307d6c652be\` FOREIGN KEY (\`cardMembersId\`) REFERENCES \`card_members\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_ae2afa612c84f4eb307d6c652be\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_554429ae7394b1fd4f26f45a623\``);
        await queryRunner.query(`ALTER TABLE \`project_members\` DROP FOREIGN KEY \`FK_d8433ad1d7964e95ddad79d2cfe\``);
        await queryRunner.query(`ALTER TABLE \`project_members\` DROP FOREIGN KEY \`FK_24cae15cf042f411ce2ccae3c1f\``);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP FOREIGN KEY \`FK_361a53ae58ef7034adc3c06f09f\``);
        await queryRunner.query(`ALTER TABLE \`boards\` DROP FOREIGN KEY \`FK_074efe1a079786d8c076bf00fff\``);
        await queryRunner.query(`ALTER TABLE \`boards\` DROP FOREIGN KEY \`FK_1ce74d5411749b559748b9f3276\``);
        await queryRunner.query(`ALTER TABLE \`board_members\` DROP FOREIGN KEY \`FK_cac1b90399803e9ec4a5e6e52a1\``);
        await queryRunner.query(`ALTER TABLE \`board_members\` DROP FOREIGN KEY \`FK_1c326eec837722d2e0879a348cc\``);
        await queryRunner.query(`ALTER TABLE \`lists\` DROP FOREIGN KEY \`FK_35ce69b6248c3fdac997094de16\``);
        await queryRunner.query(`ALTER TABLE \`cards\` DROP FOREIGN KEY \`FK_2cc808bbdb6f4e1169a8916d0a6\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_b202e040bcab8687fa432628fba\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_5fd7e1818269b78c2740fc27771\``);
        await queryRunner.query(`ALTER TABLE \`card_members\` DROP FOREIGN KEY \`FK_060d5839fbc02bdca25f57a2206\``);
        await queryRunner.query(`ALTER TABLE \`card_members\` DROP FOREIGN KEY \`FK_e635eb7677b92b43c746afb0c33\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`cardMembersId\` \`cardMembersId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`refreshTokenExpiresAt\` \`refreshTokenExpiresAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`refreshToken\` \`refreshToken\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`accessTokenExpiresAt\` \`accessTokenExpiresAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`accessToken\` \`accessToken\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`avatarUrl\` \`avatarUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_ae2afa612c84f4eb307d6c652be\` FOREIGN KEY (\`cardMembersId\`) REFERENCES \`card_members\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`userIDId\` \`userIDId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`data\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`data\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_554429ae7394b1fd4f26f45a623\` FOREIGN KEY (\`userIDId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_members\` CHANGE \`projectIDId\` \`projectIDId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_members\` CHANGE \`userIDId\` \`userIDId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`project_members\` ADD CONSTRAINT \`FK_d8433ad1d7964e95ddad79d2cfe\` FOREIGN KEY (\`projectIDId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_members\` ADD CONSTRAINT \`FK_24cae15cf042f411ce2ccae3c1f\` FOREIGN KEY (\`userIDId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`userId\` \`userId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD CONSTRAINT \`FK_361a53ae58ef7034adc3c06f09f\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`boards\` CHANGE \`projectId\` \`projectId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`boards\` CHANGE \`userId\` \`userId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`boards\` CHANGE \`visibility\` \`visibility\` enum ('workspace', 'private') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`boards\` CHANGE \`coverUrl\` \`coverUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`boards\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`boards\` ADD CONSTRAINT \`FK_074efe1a079786d8c076bf00fff\` FOREIGN KEY (\`projectId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`boards\` ADD CONSTRAINT \`FK_1ce74d5411749b559748b9f3276\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`board_members\` CHANGE \`boardIDId\` \`boardIDId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`board_members\` CHANGE \`userIDId\` \`userIDId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`board_members\` ADD CONSTRAINT \`FK_cac1b90399803e9ec4a5e6e52a1\` FOREIGN KEY (\`boardIDId\`) REFERENCES \`boards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`board_members\` ADD CONSTRAINT \`FK_1c326eec837722d2e0879a348cc\` FOREIGN KEY (\`userIDId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`lists\` CHANGE \`boardIDId\` \`boardIDId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`lists\` ADD CONSTRAINT \`FK_35ce69b6248c3fdac997094de16\` FOREIGN KEY (\`boardIDId\`) REFERENCES \`boards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`listIDId\` \`listIDId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`dueDate\` \`dueDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`startDate\` \`startDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`priority\` \`priority\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`coverUrl\` \`coverUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cards\` ADD CONSTRAINT \`FK_2cc808bbdb6f4e1169a8916d0a6\` FOREIGN KEY (\`listIDId\`) REFERENCES \`lists\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`cardIDId\` \`cardIDId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comments\` CHANGE \`userIDId\` \`userIDId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_b202e040bcab8687fa432628fba\` FOREIGN KEY (\`cardIDId\`) REFERENCES \`cards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_5fd7e1818269b78c2740fc27771\` FOREIGN KEY (\`userIDId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`card_members\` CHANGE \`userIDId\` \`userIDId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`card_members\` CHANGE \`cardIDId\` \`cardIDId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`card_members\` ADD CONSTRAINT \`FK_060d5839fbc02bdca25f57a2206\` FOREIGN KEY (\`userIDId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`card_members\` ADD CONSTRAINT \`FK_e635eb7677b92b43c746afb0c33\` FOREIGN KEY (\`cardIDId\`) REFERENCES \`cards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
